# Generated by Django 5.2.13 on 2026-04-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-executed_at',)},
        ),
    ]
