# Generated by Django 5.2.13 on 2026-04-16 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_client_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('per_share_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ex_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='portfolio.holding')),
            ],
            options={
                'ordering': ('-payment_date',),
            },
        ),
        migrations.CreateModel(
            name='TargetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('equity', 'Equity'), ('bond', 'Bond'), ('cash', 'Cash')], max_length=10)),
                ('target_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_allocations', to='portfolio.account')),
            ],
            options={
                'unique_together': {('account', 'asset_type')},
            },
        ),
    ]
